export const FETCH_HOSTS = "FETCH_HOSTS";
export const FETCH_HOSTS_SUCCESS = "FETCH_HOSTS_SUCCESS";
export const FETCH_HOSTS_FAILURE = "FETCH_HOSTS_FAILURE";
export const ADD_HOST = "ADD_HOST";
export const ADD_HOST_SUCCESS = "ADD_HOST_SUCCESS";
export const ADD_HOST_FAILURE = "ADD_HOST_FAILURE";
export const CLEAR_NEW_EVENT_ID = "CLEAR_NEW_EVENT_ID";
export const CLEAR_HOSTS = "CLEAR_HOSTS";
