export const SIGN_UP_USER_STARTED = 'SIGN_UP_USER_STARTED';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_GOOGLE_USER_STARTED = 'LOGIN_GOOGLE_USER_STARTED';
export const LOGIN_GOOGLE_USER_SUCCESS = 'LOGIN_GOOGLE_USER_SUCCESS';
export const LOGIN_GOOGLE_USER_FAILURE = 'LOGIN_GOOGLE_USER_FAILURE';
export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';

